<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'a4b64f647197b84ae3d7610508ada39f',
  'DATABASE_URL' => 'mysql://root@127.0.0.1:3306/pilefune_piscinasmartinelli?serverVersion=5.7',
  'ROOT_PATH' => '/'
);
